### PR TITLE
Add new plugin TMP117 - Temperature high precision

### PR DESCRIPTION
**Pull request by tonydee2377**
add new temperature sensor high-precision TI-TMP117

### CODE REVIEW

**Comment by tonydee2377** [comment]
Hi, 
I'm new on github, I made this plugin for Texsas Instruments TMP117 sensor for my quality control application. It was not available in your playground, I don't know if it could interest anyone and include it in the official release.

I'm testing it and it seems to work on EspEasy R148, but on the new 2.0 or mega from compilation errors of some libraries.

If anyone can help me improve and review it, I'd be grateful.
Thanks

**Comment by tonydee2377** [comment]
Help! 
is anybody there?

**Comment by TD-er** [comment]
Yeah I do read the things on the playground, but the last few days I've not written a single byte of code due to the personal changes here in house due to the Corona crisis.

**Comment by tonydee2377** [comment]
Ok excuse me,
you're right, I'm in the country most affected by Corona.

It is my first approach to github, as soon as it can I wanted to know whether to streamline the code or it is fine as it is and above all I have renamed it _P101_TMP117 but I don't know which ID to give to the plugin since 101 is busy.

Lastly, why doesn't the Devices web page update automatically? the data that I get from the sensors will not update if I don't do F5
thank you very much

**Comment by TD-er** [comment]
For the playground the id doesn't matter much, as most people will pick their own plugins and build themselves.

At least pick one above 127 and below 255 and maybe also take the first one free :)

The task values on the Devices tab do update based on their set interval value. (the interval setting in the task settings)
The JavaScript code does take the lowest of all active tasks and uses that as a refresh interval.
So if you don't use the interval setting in your plugin, you can also force a faster refresh by adding another (enabled) task that has a low interval value (e.g. a switch plugin with the interval set to 1 second)
But do realize the output values  should only be updated by a call to the `PLUGIN_READ` function.  (this will also trigger sending the values to a controller)
Some plugins do update the values in the `UserVars` array in the call to `PLUGIN_TEN_PER_SECOND` (or other periodic calls), but then only check if a value was updated and call to send data to the controllers in the `PLUGIN_READ` function.
So if your values are not updated in the devices tab, they may also not send data to a connected controller.

N.B. I have not yet looked at your code, this is just a reply to your questions.

File: _P101_TMP117.ino [hunk 1]
```diff
@@ -0,0 +1,269 @@
...
+        string += F("'>");
+        
+       // LoadTaskSettings(event->TaskIndex); // we need to restore our original taskvalues!
+        success = true;
+        break;
+      }
+
+    case PLUGIN_WEBFORM_SAVE:
+      {
+        String plugin1 = WebServer.arg("plugin_101_ConvTime");
```
Comment (TD-er) [inline _P101_TMP117.ino]: Please use the F() macro here, as this way of using regular C-strings is using a lot of memory.

File: _P101_TMP117.ino [hunk 2]
```diff
@@ -0,0 +1,269 @@
...
+uint8_t ADDR_VCC =  0x49;   // 1001001
+uint8_t ADDR_SDA =  0x4A;   // 1001010
+uint8_t ADDR_SCL =  0x4B;   // 1001011
+uint8_t ADDR =  ADDR_GND;
+uint8_t ConvTime = 0x00;
+uint8_t Averaging = 0x00;
+float offset = 0.0;
+float adjust = 0.5;
+
+TMP117 tmp(ADDR);           // I2C address for the sensor
```
Comment (TD-er) [inline _P101_TMP117.ino]: By using these global defined objects, you make it impossible to have multiple instances of this plugin active on the same node.
Also these variable names are very generic, so they are very likely to cause build issues some time as they can be used in other parts of the code as well.
Remember, these will be global defined.

Apart from that, they do take resources even when the plugin is not selected or even set enabled.

File: _P101_TMP117.ino [hunk 3]
```diff
@@ -0,0 +1,269 @@
...
+   *    1           X           print EEPROM NIST UUID [E1|E2|E3]
+   *    2         float         set temperature offset like "2 20.5" sets the offset to 20.5°C
+   *    3         float         calibrate sensor to target temperature like "3 30.5" will calibrate sensor to 30.5°C
+   * 
+   */
+        // Get sensor resolution configuration
+         uint8_t ConvTime = Settings.TaskDevicePluginConfig[event->TaskIndex][0];
+         uint8_t Averaging = Settings.TaskDevicePluginConfig[event->TaskIndex][1];
+         float adjust = Settings.TaskDevicePluginConfigFloat[event->TaskIndex][2];
+         float offset = Settings.TaskDevicePluginConfigFloat[event->TaskIndex][3];
```
Comment (TD-er) [inline _P101_TMP117.ino]: You're declaring variables here which have the same name and signature as the global variables at the beginning of this file. 
If they are only needed here, then remove the global declared ones.

File: _P101_TMP117.ino [hunk 4]
```diff
@@ -0,0 +1,269 @@
...
+        case (0x01):
+          tmp.setAveraging (AVE8);         
+          break;
+        case (0x02):
+          tmp.setAveraging (AVE32);
+          break;
+        case (0x03):
+          tmp.setAveraging (AVE64);
+          break;
+        }
```
Comment (TD-er) [inline _P101_TMP117.ino]: No `default:` case?

File: _P101_TMP117.ino [hunk 5]
```diff
@@ -0,0 +1,269 @@
...
+          break;
+        case (0x05):
+          tmp.setConvTime (C4S);
+          break;
+        case (0x06):
+          tmp.setConvTime (C8S);
+          break;
+        case (0x07):
+          tmp.setConvTime (C16S);
+          break;
```
Comment (TD-er) [inline _P101_TMP117.ino]: No `default:` case?

File: _P101_TMP117.ino [hunk 6]
```diff
@@ -0,0 +1,269 @@
...
+          tmp.setAveraging (AVE64);
+          break;
+        }       
+
+          tmp.setOffsetTemperature ( offset );      //set temperature offset
+          tmp.setTargetTemperature ( adjust );      //calibrate sensor to target temperature 
+          tmp.update();
+
+            double temperature = tmp.getTemperature();
+            UserVar[event->BaseVarIndex] = temperature;
```
Comment (TD-er) [inline _P101_TMP117.ino]: Why use a double? You don't use it anywhere else in the code, other than assigning it to the `UserVar`, which is a float.

Use of `double` on the ESP8266 is done in software as the CPU cannot deal with double resolution.
So please do a direct assign instead of storing it in a variable.

File: _P101_TMP117.ino [hunk 7]
```diff
@@ -0,0 +1,269 @@
...
+                                         //  UserVar[event->BaseVarIndex + 1] = humidity;
+            String log = F("TMP117: Temperature: ");
+            log += UserVar[event->BaseVarIndex];
+            addLog(LOG_LEVEL_INFO, log);
+            
+            success = true;
+      if(!tmp.getDeviceID())
+        {
+         success = false;
```
Comment (TD-er) [inline _P101_TMP117.ino]: If it doesn't have a device ID, why even try to set the output value first?
Apparently you do set `success` to false, so it will never register a new updated value and thus also never try to refresh it in the devices page.

File: _P101_TMP117.ino [hunk 8]
```diff
@@ -0,0 +1,269 @@
...
+        }
+      if(!success)
+        {
+          String log = F("TMP117: No reading!");
+          addLog(LOG_LEVEL_INFO, log);
+          UserVar[event->BaseVarIndex] = NAN;
```
Comment (TD-er) [inline _P101_TMP117.ino]: It is debatable if you should set a value to NaN on a failed update.
Some controllers cannot handle NaN values very well and a failed read may not always mean there will never be a valid value.
Most of the time it is perfectly fine to not update the output value if a read has failed. Setting it to NaN may also lead to other strange issues in for example rules.
Rules may address an output value directly (as in not always triggered by an updated value event), so when they encounter NaN values, their behavior may be undefined.

File: _P101_TMP117.ino (hunk 6 above)
Comment (tonydee2377) [reply _P101_TMP117.ino]: because tmp.getTemperature () only accepts double
can I use UserVar as a double?
I don't know how the plugin is structured, but from a dava or integer or float guide, I would need double
ok done
UserVar[event->BaseVarIndex] = TMP117_tmp.getTemperature();

**Comment by tonydee2377** [comment]
ok, it works.
thank you TD-er for helping me!

File: _P101_TMP117.ino [hunk 9]
```diff
@@ -0,0 +1,269 @@
...
+        optionValues[4] = (0x04);
+        options[4] = F("4 - ConvTime C1S");
+        optionValues[5] = (0x05);
+        options[5] = F("5 - ConvTime C4S");
+        optionValues[6] = (0x06);
+        options[6] = F("6 - ConvTime C8S");
+        optionValues[7] = (0x07);
+        options[7] = F("7 - ConvTime C16S");
+
+        string += F("<TR><TD>ConvTime:<TD><select name='plugin_101_ConvTime'>");
```
[the remark this answers is not in the document]
Comment (tonydee2377) [reply _P101_TMP117.ino]: but, all plugin here are structured like this,
are they all wrong then?
thanks

**Comment by TD-er** [comment]
Did you make changes that may need another commit?

**Comment by tonydee2377** [comment]
No thanks,
I have uploaded new changes _P136_TMP117.ino
 https://github.com/letscontrolit/ESPEasyPluginPlayground/pull/151/files 
Work fine!

**Comment by TD-er** [comment]
So this PR can be closed as it is essentially replaced by the other one?

**Comment by tonydee2377** [comment]
yes
